sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - /^v\d.*$/
    - master
    - develop

php:
  # Disable PHP 5.2
  # See: https://github.com/travis-ci/travis-ci/issues/8072
  # - 5.2
  - 5.6
  - 7.1

env:
  - WP_VERSION=3.8 WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=0

matrix:
  fast_finish: true
  exclude:
    - php: 5.6
      env: WP_VERSION=3.8 WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=3.8 WP_MULTISITE=0

install:
  - export DEV_LIB_PATH=dev-lib
  - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
  - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
  - source $DEV_LIB_PATH/travis.install.sh

script:
  - source $DEV_LIB_PATH/travis.script.sh

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh

before_deploy:
  - curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar > /tmp/wp-cli.phar
  - chmod +x /tmp/wp-cli.phar
  - export RELEASE_FOLDER=godaddy-email-marketing-sign-up-forms
  - php /tmp/wp-cli.phar package install runcommand/dist-archive
  - cp -r ${TRAVIS_BUILD_DIR} /tmp/${RELEASE_FOLDER}
  - mv /tmp/${RELEASE_FOLDER} ${TRAVIS_BUILD_DIR}
  - php /tmp/wp-cli.phar dist-archive ${RELEASE_FOLDER} ${TRAVIS_BUILD_DIR}/${RELEASE_FOLDER}.zip --format=zip --debug

deploy:
  provider: releases
  api_key:
    secure: jQMEnbE3F9zkrYn4WyPhDmw9ph+hs6gTY8kQyBYOA310PQkyyhKASG9i84R24DKiIUCuJhUiuVotGUCt5Y0fP/QjxwEET2IPYhhzL6lonoraGt2u0mJ9zQVJvajx+0J6auVKp9VIBucGLQPGPHECZO03cdmzYdQhLiaOhjf6vMedCLVimGu/2hDWEtQgfpZztNUMehRqDg7s8co8hlHMQa+E+mmmihRGjYjU7eMZUXF3izGFiOMKxlr9tRXNMafVwEyO/IAdeN0KZI6rYGSeegukVem+HwOTTc1ZIGS51Brr47tA46zEeWcNaPZalC35Kdfu3axNNpEWzX7AeyVJvr37klXK2Tffh9wZxGIW9mulHcvV0uOrI7d5ATEjcriMsA2tBiHaSfzQCyYcz2h7R3KiAskqXfUU9TkvhZiFjjfTWHlGTgASNsZecGa5geEnGZ/14vIAL7mfAMxi+zodviRVJ2eZdOGKXE/W5525bggD7qNrf2/upDJd8T7sma8YDpb5yuXavvQWI3dgaCSDOhDkzLTYFzwjNhiztd4YM8S/w2fqr7NmF+OqJtt7gOD5MpeGR97WbrejV3fsUSS4tirH2HddC7Xfs9dGXKusoD6Vm8TqR3w1ldok10KTnRs4LfT7XqX2Nz9nVYKh23Qr9UtmdwXRy/7mcHa8p8Mjzy8=
  file: godaddy-email-marketing-sign-up-forms.zip
  skip_cleanup: true
  overwrite: true
  on:
    repo: godaddy/wp-godaddy-email-marketing
    php: '7.1'
    condition: "$WP_VERSION=trunk"
    tags: true
